#!/usr/bin/env bash
# Runs on GitHub Actions runner. Writes production .env from environment variables.
set -euo pipefail
OUT="${1:?output path}"
cat >"$OUT" <<EOF
POSTGRES_USER=omnilearn
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
POSTGRES_DB=omnilearn
JWT_SECRET=${JWT_SECRET:-}
CORS_ORIGINS=https://omnilearn.space,https://www.omnilearn.space
FRONTEND_URL=https://omnilearn.space
NEXT_PUBLIC_API_URL=https://omnilearn.space/api
ADMIN_EMAIL=${ADMIN_EMAIL:-}
ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID:-}
LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET:-}
LINKEDIN_CALLBACK_URL=https://omnilearn.space/auth/linkedin/callback
LINKEDIN_SERVER_CALLBACK_URL=https://omnilearn.space/api/auth/linkedin/callback
NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-}
NEXT_PUBLIC_LINKEDIN_CLIENT_ID=${NEXT_PUBLIC_LINKEDIN_CLIENT_ID:-}
INTERNAL_SERVICE_KEY=${INTERNAL_SERVICE_KEY:-}
EMAIL_ENCRYPTION_KEY=${EMAIL_ENCRYPTION_KEY:-}
MAIL_FROM=${MAIL_FROM:-}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
YTDLP_MAX_QUALITY=720p
YTDLP_COOKIES_PATH=${YTDLP_COOKIES_PATH:-}
IPINFO_TOKEN=${IPINFO_TOKEN:-}
EOF
